/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/atas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Atas */
        get: operations["listar_atas_api_atas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atas/{identificador}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Ata */
        get: operations["obter_ata_api_atas__identificador__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Execucoes Rota */
        get: operations["listar_execucoes_rota_api_execucoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Execucao */
        get: operations["obter_execucao_api_execucoes__identificador__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Renomear Execucao */
        patch: operations["renomear_execucao_api_execucoes__identificador__patch"];
        trace?: never;
    };
    "/api/execucoes/{identificador}/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Resumo */
        get: operations["obter_resumo_api_execucoes__identificador__resumo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/celulas/{audiencia}/{formato}/decisao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar Decisao */
        post: operations["registrar_decisao_api_execucoes__identificador__celulas__audiencia___formato__decisao_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportar Execucao */
        get: operations["exportar_execucao_api_execucoes__identificador__exportar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/ancoras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Ancoras */
        get: operations["obter_ancoras_api_execucoes__identificador__ancoras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/celulas/{audiencia}/{formato}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Celula */
        get: operations["obter_celula_api_execucoes__identificador__celulas__audiencia___formato__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/celulas/{audiencia}/{formato}/ancoras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Ancoras Da Celula
         * @description As Âncoras numéricas citadas pela Célula final — "Âncoras ao lado da Célula".
         */
        get: operations["obter_ancoras_da_celula_api_execucoes__identificador__celulas__audiencia___formato__ancoras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/pacotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Pacotes */
        get: operations["listar_pacotes_api_execucoes__identificador__pacotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/arquivos/{caminho}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Arquivo */
        get: operations["obter_arquivo_api_execucoes__identificador__arquivos__caminho__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/filas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Filas */
        get: operations["obter_filas_api_execucoes__identificador__filas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/filas/h4/{indice}/resolver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolver Pendencia */
        post: operations["resolver_pendencia_api_execucoes__identificador__filas_h4__indice__resolver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{identificador}/pacotes/{audiencia}/{formato}/aprovar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprovar Pacote */
        post: operations["aprovar_pacote_api_execucoes__identificador__pacotes__audiencia___formato__aprovar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saude */
        get: operations["saude_api_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AncoraNumerica
         * @description Um número da Ata, com valor, unidade e o trecho literal de onde veio.
         *
         *     O Gerador copia ``valor_literal`` para dentro da Célula; o Avaliador confere por
         *     igualdade exata de valor e unidade. Nunca é reescrito por LLM.
         */
        AncoraNumerica: {
            /**
             * Chave
             * @description Chave canônica (ver ChaveAncora) ou livre.
             */
            chave: string;
            /**
             * Rotulo
             * @description Como um humano chamaria: 'Selic decidida'.
             */
            rotulo: string;
            /**
             * Valor Literal
             * @description Exatamente como a Ata escreve: '14,00', '7 a 0', '4 e 5 de agosto de 2026'.
             */
            valor_literal: string;
            /**
             * Valor
             * @description Valor numérico normalizado, quando faz sentido.
             */
            valor?: number | null;
            unidade: components["schemas"]["Unidade"];
            /**
             * Trecho
             * @description A frase literal da Ata onde o número aparece.
             */
            trecho: string;
            /**
             * Data Iso
             * @description Para unidade DATA.
             */
            data_iso?: string | null;
            /**
             * Qualificador
             * @description O que distingue 'CDI+2%' ('CDI+') de '110% do CDI' ('do CDI'); None na maioria.
             */
            qualificador?: string | null;
        };
        /**
         * AncoraTextual
         * @description Uma afirmação factual em prosa, contra a qual a Aderência textual é medida.
         */
        AncoraTextual: {
            /**
             * Identificador
             * @description Ex. 'decisao', 'balanco_de_riscos_1'.
             */
            identificador: string;
            /**
             * Afirmacao
             * @description A afirmação, em uma frase, nas palavras da Ata.
             */
            afirmacao: string;
            /**
             * Trecho
             * @description O trecho literal da Ata que a sustenta.
             */
            trecho: string;
        };
        /**
         * Ancoras
         * @description O resultado do estágio de extração: roda uma vez por Ata, antes da Matriz.
         */
        Ancoras: {
            /**
             * Ata
             * @description Identificador da Ata de origem.
             */
            ata: string;
            /** Numericas */
            numericas?: components["schemas"]["AncoraNumerica"][];
            /** Textuais */
            textuais?: components["schemas"]["AncoraTextual"][];
            /**
             * Extraida Em
             * Format: date-time
             */
            extraida_em?: string;
        };
        /**
         * Ata
         * @description O comunicado financeiro público que entra no sistema (ADR 0006).
         */
        Ata: {
            /**
             * Identificador
             * @description Nome estável do arquivo em data/atas/, ex. 'copom-280-2026-08-05'.
             */
            identificador: string;
            /** Titulo */
            titulo: string;
            /**
             * Reuniao
             * @description Número da reunião do Copom.
             */
            reuniao?: number | null;
            /**
             * Data Referencia
             * Format: date
             */
            data_referencia: string;
            /**
             * Origem Url
             * @description URL de onde o arquivo foi buscado, quando foi.
             */
            origem_url?: string | null;
            /**
             * Arquivo
             * @description Caminho local do arquivo original.
             */
            arquivo?: string | null;
            /**
             * Texto
             * @description Texto já extraído; é o que o Gerador lê.
             */
            texto: string;
            /**
             * Idioma
             * @default pt
             * @enum {string}
             */
            idioma: "pt" | "en";
        };
        /**
         * AtaResumo
         * @description A Ata sem ``texto``: a listagem não carrega o comunicado inteiro por item.
         */
        AtaResumo: {
            /** Identificador */
            identificador: string;
            /** Titulo */
            titulo: string;
            /** Reuniao */
            reuniao: number | null;
            /**
             * Data Referencia
             * Format: date
             */
            data_referencia: string;
        };
        /**
         * Audiencia
         * @description O nível de sofisticação do leitor a quem uma Célula se destina.
         * @enum {string}
         */
        Audiencia: "iniciante" | "intermediario" | "avancado";
        /**
         * AvaliacaoTransversal
         * @description Conferência determinística de completude e coerência das nove Células.
         */
        AvaliacaoTransversal: {
            estado: components["schemas"]["EstadoAvaliacaoTransversal"];
            /**
             * Total Esperado
             * @default 9
             */
            total_esperado: number;
            /** Total Recebido */
            total_recebido: number;
            /** Total Com Conteudo */
            total_com_conteudo: number;
            /** Posicoes Faltantes */
            posicoes_faltantes?: string[];
            /** Posicoes Duplicadas */
            posicoes_duplicadas?: string[];
            /** Posicoes Reprovadas */
            posicoes_reprovadas?: string[];
            /** Referencias Invalidas */
            referencias_invalidas?: string[];
            /** Observacoes */
            observacoes?: string[];
            /**
             * Avaliada Em
             * Format: date-time
             */
            avaliada_em?: string;
        };
        /**
         * BlocoFala
         * @description Um bloco de fala cronometrada do Roteiro. O primeiro bloco é o gancho.
         */
        BlocoFala: {
            /** Inicio S */
            inicio_s: number;
            /** Fim S */
            fim_s: number;
            /**
             * Fala
             * @description O que é dito. Os Limiares de Flesch-BR valem sobre isto.
             */
            fala: string;
            /**
             * Tela
             * @description Rubrica de cena: o que aparece na tela.
             * @default
             */
            tela: string;
        };
        /**
         * Celula
         * @description Uma saída concreta: uma Audiência num Formato, numa rodada do Ciclo de correção.
         */
        Celula: {
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            conteudo: components["schemas"]["Conteudo"];
            /**
             * Rodada
             * @description 0 = original; 1 e 2 = correções.
             * @default 0
             */
            rodada: number;
            /**
             * Gerada Em
             * Format: date-time
             */
            gerada_em?: string;
            /**
             * Provedor
             * @description Qual provedor gerou; nunca vai ao juiz.
             */
            provedor?: string | null;
        };
        /**
         * ConferenciaVisual
         * @description O resultado da avaliação visual do Pacote. Vai ao H5, nunca ao Laudo.
         */
        ConferenciaVisual: {
            /** Medicoes */
            medicoes?: components["schemas"]["MedicaoVisual"][];
            juiz_visao?: components["schemas"]["ParecerVisao"] | null;
        };
        /**
         * Conteudo
         * @description O texto de uma Célula, num dos três Formatos.
         *
         *     Exatamente um dos três campos de corpo é preenchido, conforme ``formato``.
         *     ``texto_avaliavel()`` devolve a prosa que as métricas medem: para o Roteiro só a fala,
         *     nunca a rubrica de cena; para o Carrossel, título e corpo de cada slide.
         */
        Conteudo: {
            formato: components["schemas"]["Formato"];
            /**
             * Texto
             * @description Texto analítico, em Markdown.
             */
            texto?: string | null;
            /** Slides */
            slides?: components["schemas"]["Slide"][] | null;
            /** Blocos */
            blocos?: components["schemas"]["BlocoFala"][] | null;
            /**
             * Ancoras Citadas
             * @description Chaves das Âncoras numéricas preenchidas em molde nesta Célula.
             */
            ancoras_citadas?: string[];
        };
        /**
         * Correcao
         * @description O que precisa mudar, com o valor medido e a distância — nunca 'melhore o texto'.
         */
        Correcao: {
            metrica: components["schemas"]["Metrica"];
            /** Valor Medido */
            valor_medido: number | null;
            faixa: components["schemas"]["Faixa"] | null;
            /**
             * Distancia
             * @description Quanto falta para entrar na Faixa.
             */
            distancia?: number | null;
            /**
             * Instrucao
             * @description Ex.: 'Flesch-BR medido 47,2; o Limiar da Audiência Iniciante é 50.'
             */
            instrucao: string;
        };
        /**
         * CorrecaoTransversalAplicada
         * @description Versão substituída e instruções enviadas de volta à persona.
         */
        CorrecaoTransversalAplicada: {
            /** Rodada */
            rodada: number;
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            /** Instrucoes */
            instrucoes: string[];
            historico_anterior: components["schemas"]["HistoricoCelula"];
        };
        /**
         * CriterioTransversal
         * @enum {string}
         */
        CriterioTransversal: "fidelidade_dossie" | "coerencia_matriz" | "progressao_personas" | "adequacao_persona" | "consistencia_formatos" | "clareza_narrativa" | "omissao_relevante" | "afirmacao_sem_evidencia";
        /**
         * Custo
         * @description Quanto custou de verdade: chamadas, tokens e tempo. Entra no relatório.
         */
        Custo: {
            /**
             * Chamadas
             * @default 0
             */
            chamadas: number;
            /**
             * Tokens Entrada
             * @default 0
             */
            tokens_entrada: number;
            /**
             * Tokens Saida
             * @default 0
             */
            tokens_saida: number;
            /**
             * Segundos
             * @default 0
             */
            segundos: number;
            /** Por Provedor */
            por_provedor?: {
                [key: string]: number;
            };
        };
        /**
         * DecisaoFila
         * @description O corpo do ``POST .../resolver``: a decisão que um humano registrou em H4.
         */
        DecisaoFila: {
            /** Decisao */
            decisao: string;
        };
        /**
         * DecisaoHumana
         * @description A decisão de um revisor sobre uma Célula. Sem registro, a Célula está pendente.
         */
        DecisaoHumana: {
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            estado: components["schemas"]["EstadoDecisao"];
            /**
             * Motivo
             * @description Obrigatório quando reprovada.
             */
            motivo?: string | null;
            /** Revisor */
            revisor?: string | null;
            /**
             * Em
             * Format: date-time
             */
            em?: string;
        };
        /**
         * DefeitoRender
         * @description O que a camada determinística da conferência visual consegue medir.
         * @enum {string}
         */
        DefeitoRender: "estouro_de_caixa" | "contraste_baixo" | "dimensao_errada" | "numero_divergente" | "duracao_fora_da_faixa" | "sem_audio";
        /**
         * Destino
         * @description Os três destinos de um Laudo (ADR 0013).
         * @enum {string}
         */
        Destino: "aprovado" | "reprovado_corrigivel" | "reprovado_revisao_humana";
        /**
         * DimensaoSubjetiva
         * @description As dimensões que só o comitê julga (ADR 0008).
         * @enum {string}
         */
        DimensaoSubjetiva: "tom" | "clareza" | "coerencia";
        /**
         * EstadoAvaliacaoTransversal
         * @description Veredito único sobre a Matriz completa, depois dos nove ciclos individuais.
         * @enum {string}
         */
        EstadoAvaliacaoTransversal: "aprovada" | "revisao_humana";
        /**
         * EstadoDecisao
         * @description O que um humano decidiu sobre uma Célula.
         * @enum {string}
         */
        EstadoDecisao: "aprovada" | "reprovada";
        /**
         * EstadoJulgamentoTransversal
         * @description Decisão do LLM Judge sobre a Matriz que já passou pelas regras fixas.
         * @enum {string}
         */
        EstadoJulgamentoTransversal: "aprovado" | "corrigivel" | "grave" | "falha";
        /**
         * EstadoMedida
         * @description Medida calculada, sem base para calcular, ou aguardando desempate humano (H3).
         * @enum {string}
         */
        EstadoMedida: "medida" | "ausente" | "revisao_humana";
        /**
         * Execucao
         * @description O único arquivo de estado de uma execução: ``data/execucoes/<id>/execucao.json``.
         */
        Execucao: {
            /** Identificador */
            identificador: string;
            /** Ata */
            ata: string;
            /** Provedor Gerador */
            provedor_gerador: string;
            /**
             * Iniciada Em
             * Format: date-time
             */
            iniciada_em: string;
            /** Concluida Em */
            concluida_em?: string | null;
            /** @description Seleção que originou o dossiê; ausente apenas em execuções antigas. */
            selecao?: components["schemas"]["SelecaoCuradoria"] | null;
            ancoras: components["schemas"]["Ancoras"];
            /** Celulas */
            celulas?: components["schemas"]["HistoricoCelula"][];
            /** Pendencias */
            pendencias?: components["schemas"]["Pendencia"][];
            custo?: components["schemas"]["Custo"];
            /**
             * Comite Ligado
             * @default false
             */
            comite_ligado: boolean;
            /** @description Veredito da Matriz completa; ausente apenas em execuções antigas. */
            avaliacao_transversal?: components["schemas"]["AvaliacaoTransversal"] | null;
            /** @description Ciclo do LLM Judge e correções; ausente apenas em execuções antigas. */
            ciclo_transversal?: components["schemas"]["ResultadoCicloTransversal"] | null;
            /**
             * Nome
             * @description Nome dado pelo usuário à Saída; vazio vira o identificador.
             * @default
             */
            nome: string;
            /**
             * Decisoes
             * @description Decisões humanas por Célula; posição sem registro está pendente.
             */
            decisoes?: components["schemas"]["DecisaoHumana"][];
        };
        /**
         * ExecucaoResumo
         * @description O que a lista de Saídas mostra sem abrir o Laudo de cada Célula.
         */
        ExecucaoResumo: {
            /** Identificador */
            identificador: string;
            /** Nome */
            nome: string;
            /** Ata */
            ata: string;
            /** Provedor */
            provedor: string;
            modo: components["schemas"]["ModoSelecao"] | null;
            /**
             * Iniciada Em
             * Format: date-time
             */
            iniciada_em: string;
            /** Aprovadas */
            aprovadas: number;
            /** Aprovadas Humano */
            aprovadas_humano: number;
            /** Total Celulas */
            total_celulas: number;
            /** Pendencias */
            pendencias: number;
            /**
             * Status
             * @enum {string}
             */
            status: "aguardando_revisao" | "concluida";
            /** Posicoes */
            posicoes: components["schemas"]["PosicaoResumo"][];
        };
        /**
         * Faixa
         * @description Intervalo fechado em ``minimo``, aberto em ``maximo``. ``None`` é sem limite daquele lado.
         */
        Faixa: {
            /** Minimo */
            minimo?: number | null;
            /** Maximo */
            maximo?: number | null;
        };
        /**
         * FilaHumana
         * @description Os pontos de interferência humana que a interface expõe como fila.
         * @enum {string}
         */
        FilaHumana: "h3_desempate" | "h4_revisao" | "h5_aprovacao_pacote";
        /**
         * Filas
         * @description As três filas humanas H3, H4 e H5, sempre listas de ``Pendencia``.
         */
        Filas: {
            /**
             * H3 Desempate
             * @default []
             */
            h3_desempate: components["schemas"]["Pendencia"][];
            /**
             * H4 Revisao
             * @default []
             */
            h4_revisao: components["schemas"]["Pendencia"][];
            /**
             * H5 Aprovacao Pacote
             * @default []
             */
            h5_aprovacao_pacote: components["schemas"]["Pendencia"][];
        };
        /**
         * Formato
         * @description A forma que uma Célula assume.
         * @enum {string}
         */
        Formato: "texto_analitico" | "carrossel" | "roteiro";
        /**
         * FormatoExportacao
         * @enum {string}
         */
        FormatoExportacao: "json" | "md" | "zip";
        /**
         * GravidadeProblemaTransversal
         * @enum {string}
         */
        GravidadeProblemaTransversal: "baixa" | "media" | "alta" | "grave";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoricoCelula
         * @description As tentativas de uma posição da Matriz, e onde ela terminou.
         */
        HistoricoCelula: {
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            /** Tentativas */
            tentativas?: components["schemas"]["Tentativa"][];
            destino_final: components["schemas"]["Destino"];
            /** Provedores Usados */
            provedores_usados?: string[];
            /**
             * Falha
             * @description Erro de provedor que interrompeu o Ciclo antes do teto, se houve. Vai à Pendencia H4.
             */
            falha?: string | null;
        };
        /** ImagemSlide */
        ImagemSlide: {
            /** Indice */
            indice: number;
            /**
             * Caminho
             * Format: path
             */
            caminho: string;
            /** Largura */
            largura: number;
            /** Altura */
            altura: number;
        };
        /**
         * JulgamentoDimensao
         * @description Dois votos por dimensão. Discordância marca REVISAO_HUMANA (H3), sem terceira chamada.
         */
        JulgamentoDimensao: {
            dimensao: components["schemas"]["DimensaoSubjetiva"];
            estado: components["schemas"]["EstadoMedida"];
            /** Votos */
            votos?: components["schemas"]["VotoJuiz"][];
            /** Consenso */
            consenso?: number | null;
        };
        /**
         * JulgamentoTransversal
         * @description Uma resposta auditável do LLM Judge, inclusive quando o provedor falha.
         */
        JulgamentoTransversal: {
            /** Rodada */
            rodada: number;
            estado: components["schemas"]["EstadoJulgamentoTransversal"];
            /** Problemas */
            problemas?: components["schemas"]["ProblemaTransversal"][];
            /** Provedor */
            provedor: string;
            /** Falha */
            falha?: string | null;
            /**
             * Avaliado Em
             * Format: date-time
             */
            avaliado_em?: string;
        };
        /**
         * Laudo
         * @description O resultado da avaliação de uma Célula: medidas, veredito e o que precisa mudar.
         */
        Laudo: {
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            /** Medidas */
            medidas: components["schemas"]["Medida"][];
            destino: components["schemas"]["Destino"];
            /** Motivos */
            motivos?: components["schemas"]["MotivoReprovacao"][];
            /** Correcoes */
            correcoes?: components["schemas"]["Correcao"][];
            /** @description None = comitê desligado. Nunca nota zero (ADR 0008). */
            comite?: components["schemas"]["ResultadoComite"] | null;
            /**
             * Avaliado Em
             * Format: date-time
             */
            avaliado_em?: string;
        };
        /**
         * MedicaoVisual
         * @description Uma medição sobre um artefato renderizado.
         */
        MedicaoVisual: {
            /**
             * Artefato
             * @description Caminho relativo da imagem ou do vídeo.
             */
            artefato: string;
            /** @description None = passou. */
            defeito?: components["schemas"]["DefeitoRender"] | null;
            /** Valor */
            valor?: number | null;
            /**
             * Detalhe
             * @default
             */
            detalhe: string;
        };
        /**
         * Medida
         * @description Uma métrica medida numa Célula, com o Limiar aplicado e o que se observou.
         */
        Medida: {
            metrica: components["schemas"]["Metrica"];
            /** @default medida */
            estado: components["schemas"]["EstadoMedida"];
            /**
             * Valor
             * @description None quando ``estado`` é AUSENTE.
             */
            valor?: number | null;
            /** @description O Limiar aplicado, se houver. */
            faixa?: components["schemas"]["Faixa"] | null;
            /**
             * Atingiu
             * @description None quando não há base para julgar.
             */
            atingiu?: boolean | null;
            /**
             * Observacoes
             * @description O que foi visto: termos sem explicação, números fora das Âncoras, a frase que recomenda.
             */
            observacoes?: string[];
        };
        /**
         * Metrica
         * @description As cinco medidas determinísticas.
         * @enum {string}
         */
        Metrica: "flesch_br" | "densidade" | "aderencia" | "recomendacao" | "integridade";
        /**
         * ModoSelecao
         * @description Como os itens aprovados pela curadoria humana alimentam a Matriz.
         * @enum {string}
         */
        ModoSelecao: "unida" | "separada";
        /**
         * MotivoReprovacao
         * @description Enumerado, não texto livre: é o que permite contar reprovação por motivo (ADR 0013).
         * @enum {string}
         */
        MotivoReprovacao: "flesch_br" | "densidade" | "aderencia" | "recomendacao" | "falha_de_extracao";
        /**
         * PacotePublicacao
         * @description O conjunto pronto para um humano publicar, só de Célula aprovada.
         */
        PacotePublicacao: {
            /** Execucao */
            execucao: string;
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            /** Legenda */
            legenda: string;
            /** Hashtags */
            hashtags?: string[];
            /** Imagens */
            imagens?: components["schemas"]["ImagemSlide"][];
            /** Folha De Contato */
            folha_de_contato?: string | null;
            /** Video */
            video?: string | null;
            conferencia?: components["schemas"]["ConferenciaVisual"];
            /**
             * Montado Em
             * Format: date-time
             */
            montado_em?: string;
            /**
             * Aprovado Por Humano
             * @default false
             */
            aprovado_por_humano: boolean;
        };
        /**
         * ParecerVisao
         * @description Resposta holística do juiz de visão sobre a folha de contato. Opcional.
         */
        ParecerVisao: {
            /** Parece Quebrado */
            parece_quebrado: boolean;
            /** Observacoes */
            observacoes?: string[];
            /** Provedor */
            provedor: string;
        };
        /**
         * PedidoDeDecisao
         * @description O corpo do ``POST .../decisao``: aprovar ou reprovar uma Célula.
         */
        PedidoDeDecisao: {
            estado: components["schemas"]["EstadoDecisao"];
            /** Motivo */
            motivo?: string | null;
            /** Revisor */
            revisor?: string | null;
        };
        /**
         * Pendencia
         * @description Uma Célula esperando decisão humana numa fila.
         */
        Pendencia: {
            fila: components["schemas"]["FilaHumana"];
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            /** Motivo */
            motivo: string;
            /**
             * Criada Em
             * Format: date-time
             */
            criada_em?: string;
            /**
             * Resolvida
             * @default false
             */
            resolvida: boolean;
            /** Decisao */
            decisao?: string | null;
        };
        /**
         * PosicaoResumo
         * @description Uma posição da Matriz, no mínimo que a tela precisa para colorir e rotular.
         */
        PosicaoResumo: {
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            destino: components["schemas"]["Destino"];
            decisao: components["schemas"]["EstadoDecisao"] | null;
            /** Bloqueada */
            bloqueada: boolean;
            /** Sem Conteudo */
            sem_conteudo: boolean;
            /** Revisao Comite */
            revisao_comite: boolean;
        };
        /**
         * ProblemaTransversal
         * @description Problema subjetivo localizado pelo Judge em uma Célula concreta.
         */
        ProblemaTransversal: {
            audiencia: components["schemas"]["Audiencia"];
            formato: components["schemas"]["Formato"];
            gravidade: components["schemas"]["GravidadeProblemaTransversal"];
            criterio: components["schemas"]["CriterioTransversal"];
            /** Evidencia */
            evidencia: string;
            /** Correcao */
            correcao: string;
        };
        /**
         * Renomeacao
         * @description O corpo do ``PATCH /api/execucoes/{id}``.
         */
        Renomeacao: {
            /** Nome */
            nome: string;
        };
        /**
         * ResultadoCicloTransversal
         * @description Estado final depois das regras fixas e do LLM Judge.
         */
        ResultadoCicloTransversal: {
            estado: components["schemas"]["EstadoAvaliacaoTransversal"];
            avaliacao_deterministica: components["schemas"]["AvaliacaoTransversal"];
            /** Julgamentos */
            julgamentos?: components["schemas"]["JulgamentoTransversal"][];
            /** Correcoes Aplicadas */
            correcoes_aplicadas?: components["schemas"]["CorrecaoTransversalAplicada"][];
            /** Motivo Final */
            motivo_final: string;
        };
        /**
         * ResultadoComite
         * @description Presente no Laudo só quando o comitê rodou. Informação, nunca Limiar de aprovação.
         */
        ResultadoComite: {
            /** Dimensoes */
            dimensoes: components["schemas"]["JulgamentoDimensao"][];
            /**
             * Provedores
             * @description Os dois provedores usados, em ordem.
             */
            provedores: string[];
        };
        /** Saude */
        Saude: {
            /** Ok */
            ok: boolean;
            /** Execucoes */
            execucoes: number;
        };
        /**
         * SelecaoCuradoria
         * @description Regra determinística da seleção: unida aceita vários itens; separada, um.
         */
        SelecaoCuradoria: {
            modo: components["schemas"]["ModoSelecao"];
            /** Itens */
            itens: string[];
        };
        /**
         * Slide
         * @description Um registro do roteiro de slides do Carrossel. O Avaliador julga o texto, não a imagem.
         */
        Slide: {
            /** Titulo */
            titulo: string;
            /** Corpo */
            corpo: string;
            /**
             * Dado
             * @description Chave da Âncora numérica a plotar neste slide, se houver (ADR 0009).
             */
            dado?: string | null;
        };
        /**
         * Tentativa
         * @description Uma rodada do Ciclo de correção: a Célula e o Laudo que a julgou.
         */
        Tentativa: {
            /** Rodada */
            rodada: number;
            celula: components["schemas"]["Celula"];
            laudo: components["schemas"]["Laudo"];
        };
        /**
         * Unidade
         * @description Unidade de uma Âncora numérica. ``p.p.`` ≠ ``%`` e ambos ≠ ``pb`` (pesquisa §3).
         * @enum {string}
         */
        Unidade: "% a.a." | "%" | "p.p." | "pb" | "votos" | "data" | "R$" | "numero";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VotoJuiz */
        VotoJuiz: {
            dimensao: components["schemas"]["DimensaoSubjetiva"];
            /** Nota */
            nota: number;
            /** Justificativa */
            justificativa: string;
            /**
             * Provedor
             * @description Qual provedor julgou. Nunca o que gerou a Célula.
             */
            provedor: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_atas_api_atas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtaResumo"][];
                };
            };
        };
    };
    obter_ata_api_atas__identificador__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_execucoes_rota_api_execucoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoResumo"][];
                };
            };
        };
    };
    obter_execucao_api_execucoes__identificador__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execucao"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renomear_execucao_api_execucoes__identificador__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Renomeacao"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoResumo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_resumo_api_execucoes__identificador__resumo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoResumo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_decisao_api_execucoes__identificador__celulas__audiencia___formato__decisao_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
                audiencia: components["schemas"]["Audiencia"];
                formato: components["schemas"]["Formato"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDeDecisao"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisaoHumana"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_execucao_api_execucoes__identificador__exportar_get: {
        parameters: {
            query: {
                formato: components["schemas"]["FormatoExportacao"];
            };
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_ancoras_api_execucoes__identificador__ancoras_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ancoras"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_celula_api_execucoes__identificador__celulas__audiencia___formato__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
                audiencia: components["schemas"]["Audiencia"];
                formato: components["schemas"]["Formato"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricoCelula"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_ancoras_da_celula_api_execucoes__identificador__celulas__audiencia___formato__ancoras_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
                audiencia: components["schemas"]["Audiencia"];
                formato: components["schemas"]["Formato"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AncoraNumerica"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_pacotes_api_execucoes__identificador__pacotes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacotePublicacao"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_arquivo_api_execucoes__identificador__arquivos__caminho__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
                caminho: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_filas_api_execucoes__identificador__filas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Filas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolver_pendencia_api_execucoes__identificador__filas_h4__indice__resolver_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
                indice: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisaoFila"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pendencia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aprovar_pacote_api_execucoes__identificador__pacotes__audiencia___formato__aprovar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
                audiencia: components["schemas"]["Audiencia"];
                formato: components["schemas"]["Formato"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacotePublicacao"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saude_api_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
}
